"""`code_index install-hooks`: write git hook scripts + wire `core.hooksPath`.

Per spec §7, code_index supports hook-driven updates for post-commit,
post-checkout, post-merge, post-rewrite. The scripts live under
`.code_index/hooks/` and are installed by setting `git config core.hooksPath`
to that directory. The CLI entrypoint the scripts call is
`python -m code_index update --files <paths> --json`, which is the same
deterministic path `init`/`update`/`watch` use.

Idempotent: running it twice produces the same on-disk state and doesn't
double-append anything. Detects when the repo isn't a git repo and prints a
clean JSON error without touching the filesystem.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import subprocess
from pathlib import Path

from code_index import config as cfg_mod


_HOOK_NAMES = ("post-commit", "post-checkout", "post-merge", "post-rewrite")


def _hook_body(hook_name: str) -> str:
    """Shell script for one hook. Determines changed paths, then calls
    `python -m code_index update --files ... --json` with them.

    Portable across Git Bash (Windows), macOS, and Linux. Silent on success;
    emits a single stderr line on failure.
    """
    return f"""#!/usr/bin/env bash
# Auto-generated by `code_index install-hooks`. Safe to re-run; the installer
# rewrites this file byte-for-byte on each invocation.
#
# Hook: {hook_name}
# Strategy:
#   * Derive changed paths from git (hook-specific).
#   * Call `python -m code_index update --files <paths> --json` once if any
#     survived the ignore filter.
#   * Fall back to `update --all` if the diff is empty for an amend/rebase.
set -euo pipefail

# Find the repo root (git already knows).
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "${{REPO_ROOT:-}}" ]; then
  exit 0
fi
cd "$REPO_ROOT"

# The index must already exist — `init` is a user action.
if [ ! -f ".code_index/index.db" ]; then
  exit 0
fi

hook_name="{hook_name}"
paths=()

case "$hook_name" in
  post-commit)
    # Files changed in HEAD.
    while IFS= read -r line; do
      [ -n "$line" ] && paths+=("$line")
    done < <(git diff --name-only HEAD~1 HEAD 2>/dev/null || git show --name-only --pretty=format: HEAD 2>/dev/null || true)
    ;;
  post-checkout)
    # Args: $1 = previous HEAD, $2 = new HEAD, $3 = branch-or-file flag.
    # Only reindex when checking out a different ref ($3 == 1).
    if [ "${{3:-}}" = "1" ]; then
      while IFS= read -r line; do
        [ -n "$line" ] && paths+=("$line")
      done < <(git diff --name-only "$1" "$2" 2>/dev/null || true)
    else
      exit 0
    fi
    ;;
  post-merge)
    # Args: $1 = squashed flag (1 = squash merge). Files changed in the merge.
    while IFS= read -r line; do
      [ -n "$line" ] && paths+=("$line")
    done < <(git diff --name-only ORIG_HEAD HEAD 2>/dev/null || true)
    ;;
  post-rewrite)
    # stdin has a list of <old-sha> <new-sha> pairs.
    rewritten=()
    while read -r old_sha new_sha; do
      [ -n "$new_sha" ] && rewritten+=("$new_sha")
    done
    if [ "${{#rewritten[@]}}" -gt 0 ]; then
      while IFS= read -r line; do
        [ -n "$line" ] && paths+=("$line")
      done < <(git diff --name-only "${{rewritten[0]}}~1" "${{rewritten[-1]}}" 2>/dev/null || true)
    fi
    ;;
esac

# Empty diff → fall back to a full sweep so history rewrites converge.
if [ "${{#paths[@]}}" -eq 0 ]; then
  python -m code_index update --all --json >/dev/null 2>&1 || true
  exit 0
fi

# Filter obvious generated/binary paths the indexer wouldn't parse anyway.
filtered=()
seen="|"
for p in "${{paths[@]}}"; do
  case "$p" in
    .git/*|.code_index/*|.claude/*|__pycache__/*|*/__pycache__/*) continue ;;
    .venv/*|venv/*|env/*|node_modules/*|dist/*|build/*|target/*) continue ;;
    *.pyc|*.pyo|*.so|*.dll|*.exe|*.png|*.jpg|*.jpeg|*.gif|*.pdf|*.zip|*.sqlite|*.db) continue ;;
  esac
  case "$seen" in
    *"|$p|"*) continue ;;
  esac
  filtered+=("$p")
  seen="${{seen}}${{p}}|"
done

if [ "${{#filtered[@]}}" -eq 0 ]; then
  exit 0
fi

if ! OUT="$(python -m code_index update --files "${{filtered[@]}}" --json 2>&1)"; then
  REL_JOINED="$(IFS=,; printf '%s' "${{filtered[*]}}")"
  OUT_TAIL="$(printf '%s' "$OUT" | tail -n 20)"
  printf 'code_index git hook %s failed for %s\\n%s\\n' "$hook_name" "$REL_JOINED" "$OUT_TAIL" >&2
fi
exit 0
"""


def _is_git_repo(root: Path) -> bool:
    return (root / ".git").exists()


def _current_hooks_path(root: Path) -> str | None:
    git = shutil.which("git")
    if not git:
        return None
    try:
        out = subprocess.run(
            [git, "-C", str(root), "config", "--local", "--get", "core.hooksPath"],
            capture_output=True,
            text=True,
            check=False,
            timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    value = (out.stdout or "").strip()
    return value or None


def _set_hooks_path(root: Path, hooks_path: Path) -> bool:
    git = shutil.which("git")
    if not git:
        return False
    # Git wants forward slashes even on Windows; str() on a Path with POSIX
    # semantics is fine because `.code_index/hooks` only has ASCII segments.
    rel = hooks_path.relative_to(root).as_posix()
    proc = subprocess.run(
        [git, "-C", str(root), "config", "--local", "core.hooksPath", rel],
        capture_output=True,
        text=True,
        check=False,
        timeout=5,
    )
    return proc.returncode == 0


def install(root: Path, *, uninstall: bool = False) -> dict:
    """Core idempotent installer. Exposed as a function so tests can drive it
    without going through argparse."""
    config = cfg_mod.load(root)
    report: dict = {
        "root": str(config.root),
        "hooks_dir": str(config.hooks_dir),
        "is_git_repo": _is_git_repo(root),
        "hooks_written": [],
        "hooks_removed": [],
        "previous_hooks_path": _current_hooks_path(root),
        "new_hooks_path": None,
        "warnings": [],
    }
    if not report["is_git_repo"]:
        report["warnings"].append(
            "Not a git repository (no .git/ found). Hook scripts were NOT "
            "written. Run `git init` first, then re-run `install-hooks`."
        )
        return report

    if uninstall:
        # Remove every known hook script if present. Keep the dir if other
        # files are in it (defensive).
        if config.hooks_dir.is_dir():
            for name in _HOOK_NAMES:
                hook = config.hooks_dir / name
                if hook.is_file():
                    hook.unlink()
                    report["hooks_removed"].append(name)
        # Unset core.hooksPath only if it currently points at our dir.
        current = report["previous_hooks_path"]
        expected = config.hooks_dir.relative_to(root).as_posix()
        if current == expected:
            git = shutil.which("git")
            if git:
                subprocess.run(
                    [
                        git,
                        "-C",
                        str(root),
                        "config",
                        "--local",
                        "--unset",
                        "core.hooksPath",
                    ],
                    capture_output=True,
                    text=True,
                    check=False,
                    timeout=5,
                )
            report["new_hooks_path"] = None
        else:
            report["new_hooks_path"] = current
        return report

    config.hooks_dir.mkdir(parents=True, exist_ok=True)
    for name in _HOOK_NAMES:
        hook = config.hooks_dir / name
        hook.write_text(_hook_body(name), encoding="utf-8", newline="\n")
        # Make executable (no-op on Windows FAT filesystems but matters on
        # everything else, including Git Bash).
        try:
            current_mode = hook.stat().st_mode
            hook.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except OSError:
            pass
        report["hooks_written"].append(name)

    if _set_hooks_path(root, config.hooks_dir):
        report["new_hooks_path"] = config.hooks_dir.relative_to(root).as_posix()
    else:
        report["warnings"].append(
            "Wrote hook scripts but could not set git config core.hooksPath. "
            "Run manually: `git config --local core.hooksPath .code_index/hooks`"
        )
        report["new_hooks_path"] = report["previous_hooks_path"]
    return report


def run(args: argparse.Namespace) -> int:
    root_hint = Path(args.root).resolve() if args.root else Path.cwd().resolve()
    root = cfg_mod.find_root(root_hint) or root_hint
    try:
        report = install(root, uninstall=args.uninstall)
    except OSError as exc:
        payload = {"error": f"filesystem error: {exc}"}
        if args.json:
            print(json.dumps(payload, indent=2))
        else:
            print(f"error: {payload['error']}")
        return 1

    if args.json:
        print(json.dumps(report, indent=2))
        return 0 if report["is_git_repo"] else 2

    if not report["is_git_repo"]:
        for w in report["warnings"]:
            print(f"warning: {w}")
        return 2

    if args.uninstall:
        if report["hooks_removed"]:
            print(f"removed hooks: {', '.join(report['hooks_removed'])}")
        else:
            print("no code_index hooks were installed")
        if report["new_hooks_path"] is None:
            print("core.hooksPath cleared")
    else:
        print(f"wrote hooks: {', '.join(report['hooks_written'])}")
        print(f"  hooks_dir:     {report['hooks_dir']}")
        print(f"  previous path: {report['previous_hooks_path']}")
        print(f"  new path:      {report['new_hooks_path']}")
        for w in report["warnings"]:
            print(f"warning: {w}")
    return 0
